# Generated by Django 4.0.1 on 2022-01-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_sender_admin',
            field=models.BooleanField(default=False),
        ),
    ]
